http:
  server:
    read_timeout: 10s
    write_timeout: 10s
    shutdown_timeout: 5s

postgres:
  host: localhost
  port: 5432
  sslmode: disable
  pool_max_conns: 10
  conn_attempts: 20
  conn_timeout: 1s

redis:

authentication:
  jwt:
    token_ttl: 15m